server:
  port: 9898

spring:
  redis:
    host: 120.79.54.26
    password: 123456
    port: 6379
  datasource:
    url: jdbc:mysql://nowcent-database.mysql.rds.aliyuncs.com:3306/wxapp_ques_test?useUnicode=true&characterEncoding=UTF8&serverTimeZone=GMT%2B8
    username: wx_ques
    password: wx-quesWX
    driver-class-name: com.mysql.cj.jdbc.Driver


  elasticsearch:
    rest:
      uris: elasticsearch.wxques.nowcent.cn

elasticsearch:
  url: elasticsearch.wxques.nowcent.cn
  port: 80


mybatis-plus:
  type-aliases-package: com.wxapp.questionnaire.pojo
  mapper-locations: classpath:mapper/*Mapper.xml


wx:
  appId: wx8747fa1dbc30f5c4
  appSecret: 323f922e8f460883a2c170a01f1094fe
  login:
    url: https://api.weixin.qq.com/sns/jscode2session





